
#Rainbow Compound settings
[config]
	#Speed multiplier for Dynamic Elytra
	#Range: 0.0 ~ 1.7976931348623157E308
	dynamic_elytra_speed = 1.0
	#Rainbow Armor Extra Defense （On the original basis）
	#Range: > 0
	rainbow_armor_exdef = 0
	#Rainbow Armor Extra Toughness （On the original basis）
	#Range: > 0
	rainbow_armor_extough = 0
	#Rainbow Tools and Weapons Extra Damage （On the original basis）
	#Range: > 0
	rainbow_tool_exdamage = 0

